name: PowerShell CI

on:
  push:
    paths:
      - '**.ps1'
      - '**.psm1'
      - '**.psd1'
      - '**.md'
  pull_request:
    paths:
      - '**.ps1'
      - '**.psm1'
      - '**.psd1'
      - '**.md'

jobs:
  lint-and-test:
    name: Lint & Test PowerShell
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        run: Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
        shell: pwsh

      - name: Run PSScriptAnalyzer
        run: Invoke-ScriptAnalyzer -Path ./ -Recurse -Severity Warning
        shell: pwsh

      - name: Run Formatter Check (dry-run)
        run: |
          $files = Get-ChildItem -Recurse -Include *.ps1, *.psm1
          foreach ($file in $files) {
            $original = Get-Content $file.FullName
            $formatted = Invoke-Formatter -ScriptDefinition ($original -join "`n")
            if (($original -join "`n") -ne ($formatted -join "`n")) {
              Write-Error "$($file.FullName) is not formatted correctly."
            }
          }
        shell: pwsh

      - name: Check for Pester tests
        run: |
          if (Test-Path ./tests) {
            Invoke-Pester -Script ./tests
          } else {
            Write-Host "No tests found. Skipping Pester."
          }
        shell: pwsh

      - name: Lint Markdown Files
        uses: avto-dev/markdown-lint@v1
        with:
          config: .markdownlint.json
          rules: ''

